sudo: required
services:
  - docker
language: node_js
node_js:
  - "node"
before_script:
  - npm install --no-optional
script:
  - npm run build
  - docker build -t crisli/reits-console .
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push crisli/reits-console
